# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d63881649851f43cc0a47ed83c5ef354f8c031bed4878334797cf52e10294bce8f5b1d827146735f80fefe6ec34935162933f4c4e717ae2a397211bf8474d07f

test:
  secret_key_base: a721ddb4e40f00179f51f1ed4f041b04253ed42c909941e2ba591900a989d9a6ecac255b314c7004d5b81a95035512cac7e5960b64ffc5c96bf6eacd10221ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
